# Vinos

## Vino tinto

### Marqués de Riscal - Rioja Reserva DOCa
Tempranillo.
Muy bueno.

### Tinto Pesquera - Crianza Ribera Del Duero
Tempranillo
Recomendado por el tío Pablo Juncosa en el verano de 2025 y probado durante la cena navideña de 2025. Muy bueno. 

### Terrazas De Los Andes - Malbec
Probamos este vino por primera vez en noviembre de 2025, cenando en casa junto a nuestros amigos Max Falkenberg (quien preparó *beef tartar*), Thomas Robiglio (quien junto a su hermano prepararon una pasta de vegetales)
y Martina Contisciani (quien preparó Focaccia). El vino recibió buenas valoraciones.

### Funckenhausen – La Espera Terroir Signature Reserva Malbec
Probamos este vino por primera vez en enero de 2026. Muy bueno.

### Coto de Imaz - Reserva Rioja DOCa
Probamos por primera vez en casa del tío Pablo en el verano de 2025. Aunque es mucho más barato que los Riojas o Ribera del Duero, es tan sabroso como ellos.


### Juan Gil - Etiqueta Amarilla D.O.P. Jumilla
Anita del Hierro y Pato Cevallos nos regalaron una botella de este vino junto con otra de Etiqueta Plata durante su visita en la Navidad de 2025.

###

## Vino Blanco

### Mayer am Pfarrplatz - Gemischter Satz
Probamos por primera vez en la boda de nuestra colega de doctorado Bela. Es el mejor vino blanco austriaco de precio asequible que conocemos.

### Primus - Sauvignon Blanc Steiermark
EStá bien, lo hemos tomado y regalado varias veces.

## Vino rosado

### Marqués de Riscal - Rosado Rioja DOCa


## Espumante

### Schlumberger - Brut

Yo (Felipe) llegué a conocer este *sekt* gracias a Ana, mi compañera cubana de clase de alemán en la primera mitad del año 2025. Se aproximaba la defensa doctoral de Gabi y andaba buscando sugerencias de bebidas para brindar. Durante un receso, Ana me lo recomendó.

Compré 6 botellas de Sparkling Brut y no sobró una gota, incluso mis amigos y colegas italianos rellenaron su copa. 

En el verano de 2025 regalamos una botella a los tíos de Gabi, Pablo y Viole (junto con una botella de la versión Rosé Brut). Más tarde, regalamos otra botella a Anita del Hierro, quien junto a Pato y Emi nos visitaron durante la navidad de 2025. En ambos casos, ha habido buena aceptación del *sekt*.

