project:
  type: book

book:
  title: "Cuaderno de Recetas, comidas y bebidas"
  author: "Gabriela Juncosa y Felipe Vaca"
  date: today
  chapters:
    - index.qmd
    - salsas.qmd
    - sopas.qmd
    - fuertes.qmd
    - panaderia.qmd
    - vinos.qmd
    
format:
  html:
    theme:
      - cosmo
      - brand
      - darkly
  pdf:
    documentclass: scrbook
    toc: true
    number-sections: true
    colorlinks: true
    pdf-engine: pdflatex