# Panadería

## Pan de masa madre

### Ingredientes
- 250 g masa madre activa (90gr masa madre, 80g harina integral, 80gr agua tibia)
- 490 g agua tibia 
- 700 g harina (560gr harina blaca tipo 700, 140 g integral)
- 20 g sal  
- 30 g aceite de oliva 

### Preparación
- Mezclar Agua y masa madre. Después, añadir harina y dejar reposar por 60 mins. 
- Stretch & fold cada 30 mins, por 6-8 veces. Añadir sal en la 4ta ocasión y aceite en la 6ta.
- Estirar la masa y formar el molde. Poner en lata.
- Tapar con tela mojada o plástico y dejar reposar en la refri por mínimo 12 horas y máximo 24.
- Calentar el horno a 200 grados C. Poner un recipientte de agua en el horno. 
- Sacar el pan de la refri y dejar reposar mientras se calienta el horno (~30 mins). Después, cortar la superficie (scorch) y rociar agua. 
- Rociar agua en la tapa y hornear el pan cubierto por 30 mins. Después, descubrir el pan y hornear por 20 mins más.
- Sacar del horno y dejar enfriar en el recipiente por 15 mins. No pasarse del tiempo, caso contrario el pan se humedece. 
- Dejar reposar fuera del recipiente por 1-2 horas antes de servir. 